In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("nba.csv")
df

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [5]:
df.tail()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.isnull().sum()

Name         1
Team         1
Number       1
Position     1
Age          1
Height       1
Weight       1
College     85
Salary      12
dtype: int64

In [10]:
df["College"] = df["College"].fillna(df["College"].mode()[0])
df["Salary"] = df["Salary"].fillna(df["Salary"].mean())

In [12]:
df.isnull().sum()

Name        1
Team        1
Number      1
Position    1
Age         1
Height      1
Weight      1
College     0
Salary      0
dtype: int64

In [14]:
df.dropna(inplace = True)

In [16]:
df.isnull().sum()

Name        0
Team        0
Number      0
Position    0
Age         0
Height      0
Weight      0
College     0
Salary      0
dtype: int64

In [22]:
age_groups = df.groupby(df["Age"])
age_groups.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7.730337e+06
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6.796117e+06
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,4.842684e+06
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1.148640e+06
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,Kentucky,5.000000e+06
...,...,...,...,...,...,...,...,...,...
299,Manu Ginobili,San Antonio Spurs,20.0,SG,38.0,6-6,205.0,Kentucky,2.814000e+06
304,Andre Miller,San Antonio Spurs,24.0,PG,40.0,6-3,200.0,Utah,2.507500e+05
306,Tony Parker,San Antonio Spurs,9.0,PG,34.0,6-2,185.0,Kentucky,1.343750e+07
400,Kevin Garnett,Minnesota Timberwolves,21.0,PF,40.0,6-11,240.0,Kentucky,8.500000e+06
420,Nazr Mohammed,Oklahoma City Thunder,13.0,C,38.0,6-10,250.0,Kentucky,2.228880e+05

In [23]:
age_groups["Salary"].describe()

,count,mean,std,min,25%,50%,75%,max
Age,,,,,,,,
19.0,2.0,1.930440e+06,2.791658e+05,1.733040e+06,1.831740e+06,1930440.0,2.029140e+06,2127840.0
20.0,19.0,2.725791e+06,1.510913e+06,5.250930e+05,1.636920e+06,2481720.0,3.954720e+06,5703600.0
21.0,19.0,2.067380e+06,1.412350e+06,5.250930e+05,1.235480e+06,1584480.0,2.084940e+06,5758680.0
22.0,26.0,2.357963e+06,1.517378e+06,5.250930e+05,1.169190e+06,1793880.0,3.366733e+06,6331404.0
23.0,41.0,2.171719e+06,2.728808e+06,3.088800e+04,6.500000e+05,1201440.0,2.891760e+06,16000000.0
24.0,47.0,3.830295e+06,4.702753e+06,5.250930e+05,9.236380e+05,1535880.0,4.751583e+06,16407501.0
25.0,45.0,3.951130e+06,4.508414e+06,5.572200e+04,9.472760e+05,1358880.0,5.543725e+06,15851950.0
26.0,36.0,6.866566e+06,6.100471e+06,1.342150e+05,1.336790e+06,3325000.0,1.256250e+07,17120106.0
27.0,41.0,6.632008e+06,6.752122e+06,5.572200e+04,1.035000e+06,3425510.0,1.123596e+07,20158622.0
28.0,31.0,5.101559e+06,4.244345e+06,2.061920e+05,1.843421e+06,4389607.0,6.190017e+06,19689000.0
29.0,28.0,6.174838e+06,4.786782e+06,1.114440e+05,2.205000e+06,5271862.5,9.322612e+06,16407500.0
30.0,31.0,6.990272e+06,5.332677e+06,9.472760e+05,3.099470e+06,5675000.0,9.000000e+06,22359364.0
31.0,22.0,8.511397e+06,7.170163e+06,9.472760e+05,3.000000e+06,5439487.0,1.347500e+07,22970500.0
32.0,13.0,7.716958e+06,7.451336e+06,2.953270e+05,3.135000e+06,5200000.0,1.121739e+07,22875000.0
33.0,14.0,3.930739e+06,4.354293e+06,2.006000e+05,1.119326e+06,2300000.0,4.040084e+06,13000000.0
34.0,10.0,7.606030e+06,5.653035e+06,2.618940e+05,4.512750e+06,6280675.5,9.103916e+06,20000000.0
35.0,9.0,3.615178e+06,2.259354e+06,9.472760e+05,1.499187e+06,3750000.0,4.842684e+06,7448760.0
36.0,10.0,2.238120e+06,1.550061e+06,9.472760e+05,9.472760e+05,1809826.0,2.888735e+06,5675000.0
37.0,4.0,1.079400e+07,9.606489e+06,4.842684e+06,4.960671e+06,6666667.0,1.250000e+07,25000000.0
38.0,4.0,1.840041e+06,1.496661e+06,2.228880e+05,7.661790e+05,1880638.0,2.954500e+06,3376000.0
39.0,2.0,2.517872e+06,2.220522e+06,9.477260e+05,1.732799e+06,2517872.5,3.302946e+06,4088019.0
40.0,3.0,4.666917e+06,4.155421e+06,2.507500e+05,2.750375e+06,5250000.0,6.875000e+06,8500000.0

df["Age"].max()

3.2

In [4]:
new_df = pd.read_csv("Iris.csv")
new_df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [27]:
new_df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [30]:
new_df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [34]:
new_df["SepalLengthCm"].describe()

count    150.000000
mean       5.843333
std        0.828066
min        4.300000
25%        5.100000
50%        5.800000
75%        6.400000
max        7.900000
Name: SepalLengthCm, dtype: float64

In [36]:
new_df["PetalLengthCm"].describe()

count    150.000000
mean       3.758667
std        1.764420
min        1.000000
25%        1.600000
50%        4.350000
75%        5.100000
max        6.900000
Name: PetalLengthCm, dtype: float64

In [5]:
new_df[new_df["Species"]=="Iris-setosa"].describe()

             Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  50.00000       50.00000     50.000000      50.000000      50.00000
mean   25.50000        5.00600      3.418000       1.464000       0.24400
std    14.57738        0.35249      0.381024       0.173511       0.10721
min     1.00000        4.30000      2.300000       1.000000       0.10000
25%    13.25000        4.80000      3.125000       1.400000       0.20000
50%    25.50000        5.00000      3.400000       1.500000       0.20000
75%    37.75000        5.20000      3.675000       1.575000       0.30000
max    50.00000        5.80000      4.400000       1.900000       0.60000